### ISSUE TITLE
FEATURE REQUEST: Password for supervision certificate

### ISSUE THREAD

**Issue by prosch88** [doronz88/pymobiledevice3#1169]
With the new supervision features there are some questions.

- Is it possible to set a password to import the certificate to an other PC?
- Is it possible to export a certificate pmd3 generated by itself?
- Are you able to import this certificate with "lockdown pair-supervised"?

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
In general, letting pmd3 generate the certificate by itself is only meant for when you really don't care about it.
If you do care, then you can use the:

```shell
pymobiledevice3 profile create-keybag /path/to/keybag
```

Then, you can transfer this keybag anywhere (doesn't require a password).
Also, if you want to export the pair-records in order to transfer them, you may simply copy them from: `~/.pymobiledevice3`
