### ISSUE TITLE
Please make reverse tcp_forwarder

### ISSUE THREAD

**Issue by vadimszzz** [doronz88/pymobiledevice3#183]
https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/tcp_forwarder.py

I can't use it to forward mobile device traffic through proxy on pc. Can it be rewrote to forward reverse way? And another one thing – I need to proxy all ports but only traffic for a specified pid, same way as pcap does with `--process` option. Can you do it or just advice what to edit in this script?

**Comment by doronz88** [comment]
I'm not sure I understand the problem. What exactly did you try to do? connect to a listening service on the iDevice side? If so, this should just work. If not, please supply with the backtrace, OS version, etc.
Or could it be that by "reverse" you mean connecting from the iDevice to a local port on your machine? If so, this should just work as-is (no lockdownd interaction required), assuming you are connected via internet sharing or by any other means on same LAN.

About forwarding by a process, this isn't really possible since the API is just for creating a tunnel. The connected processes are completely transparent to lockdownd.

**Comment by vadimszzz** [comment]
> I'm not sure I understand the problem. What exactly did you try to do? connect to a listening service on the iDevice side? If so, this should just work. If not, please supply with the backtrace, OS version, etc. Or could it be that by "reverse" you mean connecting from the iDevice to a local port on your machine? If so, this should just work as-is (no lockdownd interaction required), assuming you are connected via internet sharing or by any other means on same LAN.
> 
> About forwarding by a process, this isn't really possible since the API is just for creating a tunnel. The connected processes are completely transparent to lockdownd.

Yeah I'm talking about forwarding all device traffic or specified app through proxy. Looks like it's not possible with Lockdownd or DTXConnectionServices. But I can capture all the traffic with com.apple.pcapd and specify PID. I'll try capturing this way and decrypting SSL with frida sslkeylogger + WireShark.

**Comment by doronz88** [comment]
sniffing decrypted https like in here?
https://github.com/doronz88/harlogger
