### ISSUE TITLE
Device info malformed output

### ISSUE THREAD

**Issue by vToMy** [doronz88/pymobiledevice3#235]
I noticed some values of device info (`pymobiledevice3 lockdown info`) aren't displayed correctly, while they do display correctly in `libimobiledevice`.
Some examples:
* `ProductType` - is missing `,` in `pymobiledevice3` but not in `libimobiledevice`
* `WiFiAddress` - the `:` separator is present in the output of `libimobiledevice` but not in `pymobiledevice3`

While `WiFiAddress` output is recoverable, there's no way to restore `ProductType` from said output.

I looked into it and found the source is this peculiar "HAX":
https://github.com/doronz88/pymobiledevice3/blob/master/pymobiledevice3/service_connection.py#L48

Removing this line solves the issue.

I suppose this line is `pymobiledevice` leftover. I can only guess it was a workaround to fix some issue, but this workaround is actually causing malformed output.

**Comment by doronz88** [comment]
Thanks for the report! You are correct in assuming this is just a leftover. I handled the parsing as it should have been in the first place. All the tests pass on my iOS 14.8 device. We'll wait for @matan1008 to also review this fix before merging. Since this fix could maybe break some APIs relying on it, can you also verify everything seems to work on your end?
The PR is available here:

https://github.com/doronz88/pymobiledevice3/pull/236

**Comment by doronz88** [comment]
We've merged the change. Please verify the issue is resolved.

**Comment by vToMy** [comment]
It's resolved. Thanks.
