### ISSUE TITLE
Missing log on MAC OS

### ISSUE THREAD

**Issue by juanibonini** [doronz88/pymobiledevice3#259]
Hello Doronz! First of all I would like to congratulate you for the work on pymobiledevice3 excellent work!

I would like to ask you the following, I was using pymobiledevice and when I wanted to get the logs of my application, I realized that on mac I lose some logs. This does not happen to me on Windows, only on MAC.

I tried to find the reaseon but I can't figure. Basically I realized because I have a certain flow in my application and I can't capture logs of these flows. I wouldn't know if some additional logs are lost.

I am using the OsTraceService
I tried using other tools such as idevicesyslog to compare and I works fine.

Could you help me please?

Thanks!!

**Comment by doronz88** [comment]
Thanks for the feedback! :)

You can get the same log output as `idevicesyslog` by using the other deprecated logging API using:
```shell
pymobiledevice3 syslog live-old
```

This will use the `SyslogService` instead of `OsTraceService` which produces much less information and won't capture any DEBUG-level logs.

I don't really see how it's possible that some logs just "disappear". Could it be that the performed "grep" is just unable to capture the correct lines eventhough they do appear? Also, can you verify that the CLI interface also doesn't capture your desired output? Just so we can verify it's not a problem with your code using this relay.

**Comment by juanibonini** [comment]
Thank for your answer!

I coded something like that:

```python
for line in OsTraceService(lockdown=LockdownClient(udid=self.device.id)).syslog():
    # Write the line always and as it comes
    # Parse Log and filter
    if something in line:
        # Write parsed Log to another file
```
I use multiple services at the same time, will it have something to do with the loss of logs?

I realize that I lose logs because the flow is correct but on mac it does not leave the marks corresponding to it.

I'm going to try that and tell you how it went!

Thank you

**Comment by doronz88** [comment]
No, use of multiple services will not cause entries to disappear.
Also, I'm not sure `if something in line:` should even work. I would expect it to be `if something in line.message:` instead.

**Comment by juanibonini** [comment]
Modify the code to pseudocode to be able to explain myself better :D
