### ISSUE TITLE
is there a way to screen record ios physical devices? 

### ISSUE THREAD

**Issue by rorlig** [doronz88/pymobiledevice3#765]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by doronz88** [comment]
Video recording? 
I know only of https://github.com/danielpaulus/quicktime_video_hack
But never managed to get it work

**Comment by Valkhes** [comment]
You can only take screenshot with pymobiledevice3, so can do a stream, taking screenshot by screenshot. The FPS are going to be ridiculous. (0.5 to 1 FPS)
If you want to do something better, you can indeed checky Quicktime Video Hack. But it won't be working for iOS 17, and it's a nightmare as it's breaking a lot because of gstreamer issues.
You can also check IDB and Appium for that. Appium is maintained and you can get a stream using XCUITest, pretty easy to start, but Appium can be very hard to setup.
Not a lot of real other options sadly, that would be way easier if we had a way to compress screenshots, but the Apple service to take screenshot doesn't have any option for that.
