### ISSUE TITLE
[Help Required] Need RSD data for iOS 17

### ISSUE THREAD

**Issue by prashant1507** [doronz88/pymobiledevice3#777]
Hi,

I have a python script which runs multiple devices. No with iOS 17 I need RSD information which can be obtain using command
`sudo pymobiledevice3 remote start-tunnel`, this commands print the details and the command should keep in executing mode to keep the tunnel.

With my python script I'm trying to open Safari app and taking screenshot

So, 
how can i start and keep running command `sudo pymobiledevice3 remote start-tunnel` and use the --rsd info to take screenshot and open Safari app making sure both command runs for all the devices in parallel

Thanks

**Comment by prashant1507** [comment]
Found a work around:
`sudo pymobiledevice3 remote start-tunnel --script-mode> rsd.txt &`
`sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" rsd.txt`
then use the rsd value and once task is done kill the process ID

but is there any better way instead of above workaround

**Comment by doronz88** [comment]
I think *sudo pymobiledevice3 remote tunneld *should be a better option
since it's used as a general multiplexer for all connected devices.
You can then connect and trigger everything using: *pymobiledevice3 syslog
live --tunnel ''* or specifiy a specific device in the *--tunnel* option

‫בתאריך יום ה׳, 11 בינו׳ 2024 ב-15:57 מאת ‪Prashant Jeet Singh‬‏ <‪
***@***.***‬‏>:‬

**Comment by prashant1507** [comment]
Thank You
