### ISSUE TITLE
'Remote' command missing 

### ISSUE THREAD

**Issue by kenny12341** [doronz88/pymobiledevice3#793]
Running command on Terminal 
`python3 -m pymobiledevice3 remote start-tunnel 
`
Returns following error
`Error: No such command 'remote'.
`
Using version 2.38.1

**Comment by doronz88** [comment]
Checkout #795 and define `PYMOBILEDEVICE3_DEBUG` envvar so we can debug this

**Comment by kenny12341** [comment]
i was able to fix by

1. Uninstalling any instances of pymobiledevice3
2. Upgrading latest version of Python (3.9.X => 3.11.7)
3. Reinstalling pymobiledevice3 via pip

This seems to have installed all the required dependencies successfully

**Comment by vToMy** [comment]
@doronz88 
I got this error as well on python 3.11 on windows, and it seems the cause was an import error caused by `sslpsk` (which is silently swallowed)
I suspect this package does not support python 3.11 on windows.
Since this package is only for TCP tunnels it's not mandatory, so I think we can lazy-load it to avoid this error.

**Comment by doronz88** [comment]
I'm maybe mistaken, but I'm the owner of this package and I believe the CI should provide all required wheels:
https://pypi.org/project/sslpsk-pmd3/#files

I could silently ignore it, but I suspect the problem comes from pulling the new sources directly from git without re-installing the package with it's requirements?

**Comment by doronz88** [comment]
@vToMy after someone else reported he was indeed encountering the same issue on windows after reinstalling the package I created a PR for it - waiting for either you or him to tell me if this resolves the issue
