### ISSUE TITLE
[Feature Request] Keys and Mouse support over USB

### ISSUE THREAD

**Issue by prashant1507** [doronz88/pymobiledevice3#827]
Support for sending keyboard events and touchpad/mouse events over USB while the device is connected to the System using a USB (or a tunnel)

**Comment by nanoscopic** [comment]
While the device is connected via USB, the iOS device is in client mode. This means accessories such as synthetic USB devices ( gadgets ) cannot then be created by something on the host and interact with the device.

In order to do this the phone would have to stay in host mode and be connected to pmd3 via wifi or an ethernet dongle, and then the host would need to be connected to the device as a client of the iOS device and operate in gadget mode.

To do that you'd need to use an embedded board put into gadget mode also I believe.

This request is, essentially, out of scope for what pmd3 does.

**Comment by doronz88** [comment]
@nanoscopic is correct (and thanks for ellaborating so much on the topic! 🙂)
pymobile's scope is for utilizing the set of protocols exposed by the iOS device over USB/WiFi to communicate with the device and attempting to provide a simple enough API to access them all.

**Comment by nanoscopic** [comment]
I'll add slightly more detail for those who want to do this.

You can trigger synthetic key entry two ways using WebDriverAgent. You can in turn start WebDriverAgent on a device using pmd3 on devices before iOS 17. The "iohid" method lets you somewhat directly initiate keystrokes, but only supports keystrokes that are lowercase. shift-modifiers are not supported for iohid. For help and more information on that see the WebDriverAgent project by Appium.

For synthetic mouse events, those also can be created with WDA. WDA under the hood is generating "synthetic events" that are a tap at a certain position using the XCTest API.

The XCTest API cannot be called directly over usbmuxd/lockdown, hence me saying it is out of scope for this project.
