### ISSUE TITLE
[QA] Is iOS 17 tunnel backward compatible with older iOS?

### ISSUE THREAD

**Issue by wojciech-kulik** [doronz88/pymobiledevice3#844]
Hi!

I'm working to integrate this tool with my plugin [xcodebuild.nvim](https://github.com/wojciech-kulik/xcodebuild.nvim). I've got only 2 devices, one with iOS 14 and one with iOS 17.

I would like to know if the approach with [tunnel](https://github.com/doronz88/pymobiledevice3?tab=readme-ov-file#working-with-developer-tools-ios--170) works only on iOS 17+ or does it work also on iOS 15-17.

As far as I was able to test it, it doesn't work on iOS 14.

Thank you in advance!

**Comment by doronz88** [comment]
Yeah, the tunnel is part of the new CoreDevice framework Apple officially added on iOS 17 and refactored all the Developer-related stuff to go only through it - meaning in order to support all variations you'll have to support both options.
That is also the reason why every pymobile command receives an optional `--tunnel/--rsd` option and not forces one on the user, since it's just another layer of abstraction to access each service and different variations work on different cases

**Comment by wojciech-kulik** [comment]
Great, thank you for the explanation!
